name: CI Sistema Educativo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: usuarios-servicio
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Primero construye todos los proyectos
      - name: Build all services
        run: |
          mvn -f config-server/pom.xml clean package -DskipTests
          mvn -f eureka-server/pom.xml clean package -DskipTests
          mvn -f usuarios-servicio/pom.xml clean package -DskipTests
          mvn -f asignaturas-servicio/pom.xml clean package -DskipTests
          mvn -f matriculas-servicio/pom.xml clean package -DskipTests

      # Luego construye los contenedores
      - name: Build and start containers
        run: |
          docker-compose up -d --build

      - name: Wait for services
        run: sleep 60

      # Finalmente ejecuta los tests
      - name: Run tests
        run: |
          mvn -f usuarios-servicio/pom.xml test
          mvn -f asignaturas-servicio/pom.xml test
          mvn -f matriculas-servicio/pom.xml test