jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Docker Compose
        run: sudo apt-get install docker-compose -y

      # 👇 ESTE ES EL PASO QUE FALTABA
      - name: Compilar config-server
        run: |
          cd config-server
          mvn clean package -DskipTests
          cd ..

      - name: Construir y levantar los servicios
        run: docker-compose up -d --build

      - name: Esperar a que los servicios estén listos
        run: sleep 40

      - name: Verificar contenedores
        run: docker ps -a

      - name: Instalar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ejecutar pruebas de usuarios-servicio
        run: |
          cd usuarios-servicio
          mvn clean test

      - name: Ejecutar pruebas de asignaturas-servicio
        run: |
          cd asignaturas-servicio
          mvn clean test

      - name: Ejecutar pruebas de matriculas-servicio
        run: |
          cd matriculas-servicio
          mvn clean test
