name: CI para Sistema Educativo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-config-server:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construir Config Server
        run: |
          cd config-server
          mvn clean install -DskipTests=false

  build-usuarios-servicio:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construir Usuarios Servicio
        run: |
          cd usuarios-servicio
          mvn clean install -DskipTests=false