name: CI Sistema Educativo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Clona el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Instala Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Construcción de todos los módulos con Maven
      - name: Build all modules
        run: mvn -B clean install -DskipTests

      # Construcción de imágenes Docker
      - name: Build Docker images
        run: docker-compose build

      # Inicia los contenedores de Docker en segundo plano
      - name: Start containers
        run: docker-compose up -d

      # Espera a que los servicios estén listos
      - name: Wait for services
        run: sleep 30

      # Ejecuta las pruebas
      - name: Run tests
        run: mvn test

      # Finaliza y elimina los contenedores y redes de Docker
      - name: Tear down Docker containers
        if: always() # Asegura que este paso se ejecuta aunque el pipeline falle
        run: docker-compose down -v